In [139]:
import numpy  as np
import pandas as pd

# 시각화
import matplotlib.pyplot as plt 
%matplotlib inline

import seaborn as sns

import json 

import warnings
warnings.filterwarnings(action='ignore')

from datetime import date, datetime, timedelta
from dateutil.parser import parse


# 한글 폰트 문제 해결
import platform

from matplotlib import font_manager, rc

if platform.system() == 'Darwin':
    plt.rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    path = "c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    plt.rc('font', family=font_name)
else:
    print('Unknown system... sorry~~~~') 


# 차트 축 <- 음수 부호 지원
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False


# crawling
from bs4 import BeautifulSoup
from urllib.request import urlopen , urlretrieve
from urllib.error   import HTTPError
from urllib.error   import URLError

import requests 
import re

from selenium import webdriver

from time    import sleep , time 
from random  import randint
from IPython.core.display import clear_output

# 비정형 디비 
import pymongo as mongo

# print('numpy version  - ' , np.__version__)
# print('pandas version - ' , pd.__version__)

# conda install -c conda-forge python-graphviz
# pip install graphviz

import graphviz
import missingno as msno

# ml 
import sklearn
from   sklearn.datasets import load_iris , load_breast_cancer

from   sklearn.model_selection import train_test_split , KFold , StratifiedKFold, cross_val_score , cross_validate , GridSearchCV

from   sklearn.tree            import DecisionTreeClassifier , export_graphviz
from   sklearn.ensemble        import RandomForestClassifier
from   sklearn.linear_model    import LogisticRegression


from   sklearn.metrics         import accuracy_score , precision_score , recall_score , f1_score , confusion_matrix , RocCurveDisplay , roc_auc_score
from   sklearn.preprocessing   import LabelEncoder , OneHotEncoder , MinMaxScaler , StandardScaler , Binarizer
from   sklearn.impute          import SimpleImputer
from   sklearn.base          import BaseEstimator 

from   IPython.display import Image


sklearn.__version__

'0.24.2'

In [140]:
def metrics_evaluation(target , prediction) :
    print('confusion matrix \n' , confusion_matrix(target , prediction))
    print()
    print('accuracy \n' , accuracy_score(target , prediction))
    print()
    print('recall \n'   , recall_score(target , prediction))
    print()
    print('precision \n'   , precision_score(target , prediction))
    print()
    print('f1 score \n'   , f1_score(target , prediction))

In [27]:
diabets = pd.read_csv('C:/Users/crid2/ml-data/classification-diabetes.csv')
diabets.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [156]:
# age가 0인 값을 평균으로 대체했다. 판다스 replace 함수 사용 

diabets['Age'] = diabets['Age'].replace(0 , SimpleImputer(diabets['Age'] , strategy='mean'))

In [157]:
diabets.discribe()

AttributeError: 'DataFrame' object has no attribute 'discribe'

In [110]:
diabets['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

-Pregnancies: 임신 횟수 

-Glucose: 포도당 부하 검사 수치

-BloodPressure: 혈압(mm Hg)

-SkinThickness: 팔 삼두근 뒤쪽의 피하지방 측정값(mm)

-Insulin: 혈청 인슐린(mu U/ml)

-BMI: 체질량지수(체중(kg)/(키(m))^2)

-DiabetesPedigreeFunction: 당뇨 내력 가중치 값

-Age: 나이

-Outcome: 클래스 결정 값(0또는 1)


In [111]:
# target 은 outcome 으로 정한다. , 트레인값이 0이 2배 더 많다. acc만으로는 성능이 왜곡된다. 
# 다양한 형태의 성능 평가가 필요하다. 
# label 작업은 필요없어보인다. 
# 정규화가 필요한가 ? age에 정규화는 오히려 안좋을것같다. 

- 실습가이드 
- LogisticRegression 학습 예측 수행 
- 0값이 있는 피처들에서 값의 데이터 건수와 퍼센트 계산 
- 0값을 평균으로 대체
- 모든 피처에 대해서 일괄적으로 스케일링 적용 ( 정규화 , 표준화 )
- 재현율 P/N 이라고하는 확률 recall 성능 측정 - 시각화 

In [117]:
diabets.target = diabets.iloc[:,-1]
diabets.data = diabets.iloc[:, :-1]

In [113]:
X_train , X_test , y_train , y_test = train_test_split(diabets.data , 
                                                       diabets.target , 
                                                       test_size = 0.2 , 
                                                       random_state = 100)

X_train.shape , X_test.shape , y_train.shape , y_test.shape 

((614, 8), (154, 8), (614,), (154,))

In [162]:
# 표준화 진행 

dia_model01 = LogisticRegression()

s_scale = StandardScaler()
s_scale.fit(X_train)

strain_data = s_scale.transform(X_train)
stest_data = s_scale.transform(X_test)


dia_model01.fit(strain_data, y_train)
y_pred = dia_model01.predict(stest_data)

accuracy_score(y_test, y_pred)


0.7337662337662337

In [181]:
# 정규화 진행 
dia_model02 = RandomForestClassifier()

m_scale = MinMaxScaler()
m_scale.fit(X_train)

mtrain_data = m_scale.transform(X_train)
mtest_data = m_scale.transform(X_test)


dia_model02.fit(mtrain_data, y_train)
y_pred = dia_model02.predict(mtest_data)

accuracy_score(y_test, y_pred)


0.7142857142857143

In [183]:
# 최적의 파라메터 GridSearchCV 사용 
params02 = {'max_depth' : [2,3,5,10],
         'min_samples_split' : [2,3,5],
         'min_samples_leaf':[1,5,8]}

params03 = {
    'criterion' : ['gini' , 'entropy'],
    'splitter' : ['best' , 'random'], # spllitter라고 했다. 오타 주의 
    'max_depth' : [1,2,3] , 
    'min_samples_split' : [2, 3 ]
}
params = {
    'n_estimators' : [200, 300] , 
    'max_features' : [6, 8, 15, 20] , 
    'max_depth'    : [4, 6, 8]
}



In [203]:
# lr params 
param_lr = {
      'max_iter' : [10,50,100] 
         }

In [216]:
gsc_model_01 = GridSearchCV(dia_model01, param_grid=param_lr, cv=10 , refit=True ,scoring='recall')
gsc_model_01.fit(X_train , y_train)


GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'max_iter': [10, 100]}, scoring='recall')

In [217]:
estimator = gsc_model_01.best_estimator_
y_pred = estimator.predict(X_test)
metrics_evaluation(y_test , y_pred)

confusion matrix 
 [[87 14]
 [24 29]]

accuracy 
 0.7532467532467533

recall 
 0.5471698113207547

precision 
 0.6744186046511628

f1 score 
 0.6041666666666666


In [215]:
gsc_model_02 = GridSearchCV(dia_model02, param_grid=params, cv=10 , refit=True ,scoring='recall')
gsc_model_02.fit(strain_data , y_train)


GridSearchCV(cv=10, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [4, 6, 8], 'max_features': [6, 8, 15, 20],
                         'n_estimators': [200, 300]},
             scoring='recall')

In [218]:
estimator = gsc_model_02.best_estimator_
y_pred = estimator.predict(stest_data)

In [219]:
metrics_evaluation(y_test , y_pred)

confusion matrix 
 [[85 16]
 [24 29]]

accuracy 
 0.7402597402597403

recall 
 0.5471698113207547

precision 
 0.6444444444444445

f1 score 
 0.5918367346938775


In [221]:
### 재현율 정확도 

logistic_model = LogisticRegression()

logistic_model.fit(X_train , y_train) 
y_pred = logistic_model.predict(X_test) 

metrics_evaluation(y_test , y_pred)

confusion matrix 
 [[87 14]
 [24 29]]

accuracy 
 0.7532467532467533

recall 
 0.5471698113207547

precision 
 0.6744186046511628

f1 score 
 0.6041666666666666


In [223]:
print('확률예측 값 - predict_proba() ') 

predict_proba_result = logistic_model.predict_proba(X_test)
print('type  - ' , type(predict_proba_result))
print('shape - ' , predict_proba_result.shape)
print()
print('type  - ' , type(y_pred))
print('shape - ' , y_pred.shape)

확률예측 값 - predict_proba() 
type  -  <class 'numpy.ndarray'>
shape -  (154, 2)

type  -  <class 'numpy.ndarray'>
shape -  (154,)


In [225]:
print('예측값과 예측확률값의 병합 - ') 
pred_prob_concat =  np.concatenate( [ predict_proba_result , y_pred.reshape(-1, 1) ] , axis = 1)
pred_prob_concat  

예측값과 예측확률값의 병합 - 


array([[0.83154189, 0.16845811, 0.        ],
       [0.93488062, 0.06511938, 0.        ],
       [0.28612423, 0.71387577, 1.        ],
       [0.87744415, 0.12255585, 0.        ],
       [0.55161408, 0.44838592, 0.        ],
       [0.30003968, 0.69996032, 1.        ],
       [0.02750797, 0.97249203, 1.        ],
       [0.88123812, 0.11876188, 0.        ],
       [0.13494244, 0.86505756, 1.        ],
       [0.7708846 , 0.2291154 , 0.        ],
       [0.89868089, 0.10131911, 0.        ],
       [0.13595352, 0.86404648, 1.        ],
       [0.54375788, 0.45624212, 0.        ],
       [0.71197326, 0.28802674, 0.        ],
       [0.27769257, 0.72230743, 1.        ],
       [0.66401191, 0.33598809, 0.        ],
       [0.90611811, 0.09388189, 0.        ],
       [0.77815406, 0.22184594, 0.        ],
       [0.48297955, 0.51702045, 1.        ],
       [0.78885134, 0.21114866, 0.        ],
       [0.72910577, 0.27089423, 0.        ],
       [0.98294143, 0.01705857, 0.        ],
       [0.

In [227]:
print('threshold 0.5 (default) - ') 
print()
metrics_evaluation(y_test , y_pred)

threshold 0.5 (default) - 

confusion matrix 
 [[87 14]
 [24 29]]

accuracy 
 0.7532467532467533

recall 
 0.5471698113207547

precision 
 0.6744186046511628

f1 score 
 0.6041666666666666


In [229]:
print('positive value - ')
predict_proba_positive = predict_proba_result[ :  , 1].reshape(-1, 1)

user_th = 0.3
user_th_pred = Binarizer(threshold = user_th).fit_transform(predict_proba_positive)

print('user th 0.3 - ') 
metrics_evaluation(y_test , user_th_pred)

positive value - 
user th 0.3 - 
confusion matrix 
 [[69 32]
 [12 41]]

accuracy 
 0.7142857142857143

recall 
 0.7735849056603774

precision 
 0.5616438356164384

f1 score 
 0.6507936507936508
